const sidebar = {
  "/base/1.html/": [
    "1.三栏布局",
    //移动端开发
    "1.index",
    "1.page",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
  ],
  "/base/2.css/": ["1.清除浮动", "2.3d旋转色子", "3.水平垂直居中"],
  "/base/3.js/": [
    "1.index",
    "1.grammar",
    "2.morphology",
    "3.context",
    "4.variableobj",
    "5.scope",
    "6.closure",
    "7.this",
    "8.async",
    "9.eventloop",
  ],
  "/base/4.dom/": [
    "1.index",
    "10.正则表达式及实战",
    "11.JSON和JSON的解析",
    "12.事件、事件传播和委托",
    "13.event",
    "14.事件原理和自定义事件",
    "15.事件驱动和事件发射器",
    "16.拖拽和原生拖拽事件",
    "17.手机的 touch gesture 事件模型",
    "22.Ajax 同源策略和跨域",
    "26.内存管理",
  ],
  "/base/5.type/": [
    "1.index",
    "1.number",
    "2.string",
    "3.boolean",
    "4.undefined",
    "5.null",
    "6.object",
    "7.array",
    "8.reference",
    "9.extend",
    "9.function",
    "10.prototype",
    "12.copy",
  ],
  "/base/project/": ["1.index", "1.uml"],
  "/source/promise/": ["1.index"],
  "/source/browser/": [
    "1.index",
    "1.browser",
    "2.tree",
    "3.reflow",
    "4.async",
    "5.eventLoop",
    "6.microtaskMacrotask",
    "7.crp",
    "8.skeleton",
    "9.test",
  ],
  "/source/api/": ["1.index"],
  "/base/es6/": [
    //五、ES6+核心知识和源码分析
    "1.scope",
    "2.constant",
    "3.deconstruction",
    "4.string",
    "5.function",
    "6.object",
    "7.class",
    "8.general",
    "9.collect",
    "10.module",
  ],
  // 专项知识
  "/special/optimize/": [
    //性能优化
    "1.index",
    "1.cdn", //cdn
    "2.canvas", //缓存
    "3.store",
    "4.img",
    "5.api",
    "6.form",
    "7.seo",
    "9.lazy",
    "10.ssr", //服务端渲染
    "11.debounceAndThrottle", //防抖与节流
    "12.webpack",
  ],
  "/special/standard/": ["1.index"],
  "/special/monitor/": [
    //前端监控
    "1.index",
  ],
  "/special/security/": [
    //前端安全
    "1.index",
    "1.xss",
    "2.csrf",
    "3.doos",
    "4.http",
  ],
  "/special/design/": [
    //设计模式
    "1.index",
    "1.factory",
    "2.abstract",
    "3.single",
    "4.prototype",
    "5.made",
    "6.adapter",
    "7.decorator",
    "8.proxy",
    "9.appearance",
    "10.pickup",
    "11.combination",
    "12.flyweight",
    "13.strategy",
    "14.module",
    "15.observer",
    "16.iterator",
    "17.chain",
    "18.command",
    "19.memorandum",
    "20.state",
    "21.visitor",
    "22.mediator",
    "23.interpreter",
  ],
  "/special/cross/": [
    //跨域
    "1.index",
    "1.browser",
    "2.cors",
    "3.nginx",
    "4.http-proxy-middleware",
    "5.jsonp",
    "6.domain",
    "7.name",
    "8.hash",
    "9.postMessage",
    "10.webSocket",
  ],
  "/special/test/": [
    // 测试
    "1.index",
  ],
  "/special/regexp/": [
    // 测试
    "1.index",
  ],
  "/special/http/": [
    // 测试
    "1.index",
    "1.http",
    "2.https",
    "3.tcp",
    "4.catch",
    "5.dns",
  ],
  // 高级知识
  "/senior/micro/": ["1.index"],
  "/senior/file/": ["1.index"],
  "/senior/crossDomain/": [
    //跨域
    "inde",
    "1.demote",
    "2.cors",
    "3.nginx",
    "4.http-proxy-middleware",
    "5.jsonp",
    "6.domain",
    "7.name",
    "8.hash",
    "9.postMessage",
    "10.webSocket",
  ],
  "/read/book1/": [
    "1.index",
    "chapter1",
    "chapter2",
    "chapter3",
    "chapter4",
    "chapter5",
    "chapter6",
    "chapter7",
  ],
  "/read/book2/": [
    "1.index",
    "chapter1",
    "chapter2",
    "chapter3",
    "chapter4",
    "chapter5",
    "chapter6",
    "chapter7",
  ],
  "/read/book3/": [
    "1.index",
    "chapter1",
    "chapter2",
    "chapter3",
    "chapter4",
    "chapter5",
    "chapter6",
    "chapter7",
  ],
  "/read/book4/": [
    "1.index",
    "chapter1",
    "chapter2",
    "chapter3",
    "chapter4",
    "chapter5",
    "chapter6",
    "chapter7",
  ],
  "/read/book5/": [
    "1.index",
    "chapter1",
    "chapter2",
    "chapter3",
    "chapter4",
    "chapter5",
    "chapter6",
    "chapter7",
  ],
};
module.exports = sidebar;
