const sidebar = {
  "/1.base/1.js/": [
    "1.index",
    "1.grammar",
    "2.morphology",
    "3.context",
    "4.variableobj",
    "5.scope",
    "6.closure",
    "7.this",
    "8.async",
    "9.eventloop",
    "10.dom",
    "11.bom",
  ],
  "/1.base/2.dom/": [
    "1.index",
    // '1.element',
    // '2.attrs',
    // '3.events',
    // '4.code',
  ],
  "/1.base/3.bom/": [
    "1.index",
    // "1.grammar",
    // "2.select",
    // "3.position",
    // "4.layout",
    // "5.style",
    // '6.animation',
    // '7.yong'
  ],
  "/2.advanced/1.h5/": [
    "1.index",
  ],
  "/2.advanced/2.js/": [
    "1.index",
    "1.grammar",
    "2.morphology",
    "3.context",
    "4.variableobj",
    "5.scope",
    "6.closure",
    "7.this",
    "8.async",
    "9.eventloop",
  ],
  "/2.advanced/3.type/": [
    "1.index",
    "1.number",
    "2.string",
    "3.boolean",
    "4.undefined",
    "5.null",
    "6.symbol",
    "7.object",
    "8.array",
    "9.function",
    "10.judge",
    "11.transform",
    "12.copy",
  ],
  "/2.advanced/6.es6/": [
    "1.index",
    "1.scope",
    "2.constant",
    "3.deconstruction",
    "4.string",
    "5.function",
    "6.object",
    "7.class",
    "8.general",
    "9.collect",
    "10.module",
  ],
  "/3.senior/2.design/": [
    "1.index",
    "1.factory",
    "2.abstract",
    "3.single",
    "4.prototype",
    "5.made",
    "6.adapter",
    "7.decorator",
    "8.proxy",
    "9.appearance",
    "10.pickup",
    "11.combination",
    "12.flyweight",
    "13.strategy",
    "14.module",
    "15.observer",
    "16.iterator",
    "17.chain",
    "18.command",
    "19.memorandum",
    "20.state",
    "21.visitor",
    "22.mediator",
    "23.interpreter",
  ],
  "/3.senior/5.optimize/": [
    "1.index",
    "1.cdn", //cdn
    "2.canvas", //缓存
    "3.store",
    "4.img",
    "5.api",
    "6.form",
    "7.seo",
    "9.lazy",
    "10.ssr", //服务端渲染
    "11.debounceAndThrottle", //防抖与节流
    "12.webpack",
  ],
  "/3.senior/6.debugger/": [
    "1.index",
  ],
  "/3.senior/7.cross/": [
    //跨域
    "1.index",
    "1.browser",
    "2.cors",
    "3.nginx",
    "4.middleware",
    "5.jsonp",
    "6.domain",
    "7.name",
    "8.hash",
    "9.postMessage",
    "10.webSocket",
  ],
  "/4.special/1.cli/": [
    "1.index",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
  ],
  "/4.special/2.package/": [
    "1.index",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "13",
    "14",
  ],
  "/4.special/3.dev/": [
    "1.index"
  ],
  "/4.special/4.construct/": [
    "1.index"
  ],
  "/4.special/5.project/": [
    "1.index",
    "1.uml"
  ],
  "/4.special/5.standard/": [
    "1.index"
  ],
  "/4.special/6.test/": [
    "1.index",
  ],
  "/4.special/7.cicd/": [
    "1.index",
  ],
  "/4.special/8.monitor/": [
    "1.index",
  ],
  // "/5.scene/1.micro/": [
  //   "1.index",
  //   '1.singlespa',
  //   '2.qiankun'
  // ],
  "/5.scene/2.file/": [
    "1.index"
  ],
  "/5.scene/3.video/": [
    "1.index",
  ],
  "/6.source/1.promise/": [
    "1.index",
    "1",
    "2"
  ],
  "/6.source/browser/": [
    "1.index",
    "1.browser",
    "2.tree",
    "3.reflow",
    "4.async",
    "5.eventLoop",
    "6.microtaskMacrotask",
    "7.crp",
    "8.skeleton",
    "9.test",
  ],
  "/6.source/api/": [
    "1.index"
  ],
  "/7.read/book1/": [
    "1.index",
    "chapter1",
    "chapter2",
    "chapter3",
    "chapter4",
    "chapter5",
    "chapter6",
    "chapter7",
  ],
  "/7.read/book2/": [
    "1.index",
    "chapter1",
    "chapter2",
    "chapter3",
    "chapter4",
    "chapter5",
    "chapter6",
    "chapter7",
  ],
  "/7.read/book3/": [
    "1.index",
    "chapter1",
    "chapter2",
    "chapter3",
    "chapter4",
    "chapter5",
    "chapter6",
    "chapter7",
  ],
  "/7.read/book4/": [
    "1.index",
    "chapter1",
    "chapter2",
    "chapter3",
    "chapter4",
    "chapter5",
    "chapter6",
    "chapter7",
  ],
  "/7.read/book5/": [
    "1.index",
    "chapter1",
    "chapter2",
    "chapter3",
    "chapter4",
    "chapter5",
    "chapter6",
    "chapter7",
  ],
};
module.exports = sidebar;
